org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=false
org.gradle.daemon=true
org.gradle.caching=true

mod_name=Powah! Refabricated
mod_version=7.0.4
archives_base_name=Powah-Refabricated-fabric-26.1.2
maven_group=dev.technici4n

minecraft_version=26.1.2
fabric_loader_version=0.19.5
fabric_api_version=0.155.3+26.1.2
team_reborn_energy_version=5.0.0
cloth_config_version=26.1.154
rei_version=26.1.819
jei_version=29.43.0.105
trinkets_version=4.0.1+26.1
